#!/bin/bash

# Get amixer info once
AMIXER_OUTPUT=$(amixer -D default sget Master 2>/dev/null)

# Get mute status
if echo "$AMIXER_OUTPUT" | grep -q '\[off\]'; then
    IS_MUTED="true"
else
    IS_MUTED="false"
fi

# Get volume
VOLUME=$(echo "$AMIXER_OUTPUT" | grep -oP '\[\K\d+(?=%\])' | head -1)
VOLUME=${VOLUME:-0}

# Determine icon
if [[ "$IS_MUTED" == "true" ]]; then
    ICON=""
elif [[ $VOLUME -eq 0 ]]; then
    ICON=""
elif [[ $VOLUME -le 33 ]]; then
    ICON=""
elif [[ $VOLUME -le 66 ]]; then
    ICON=""
else
    ICON=""
fi

# Output requested argument
case "$1" in
    "icon")
        echo "$ICON"
        ;;
    "volume")
        echo "$VOLUME"
        ;;
    *)
        echo "$VOLUME"
        ;;
esac
